//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SMS.server {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sSetDefaultAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback sChangeLibrarianOperationCompleted;
        
        private System.Threading.SendOrPostCallback sValidAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback sAddParentOperationCompleted;
        
        private System.Threading.SendOrPostCallback sAddStudentOperationCompleted;
        
        private System.Threading.SendOrPostCallback sValidLibrarianOperationCompleted;
        
        private System.Threading.SendOrPostCallback sViewAllBooksOperationCompleted;
        
        private System.Threading.SendOrPostCallback sViewBookByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback sViewBookByAuthorOperationCompleted;
        
        private System.Threading.SendOrPostCallback sAddBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback sRemoveBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback sViewBookNamesOperationCompleted;
        
        private System.Threading.SendOrPostCallback sMarkAttendanceEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback sViewEmployeeNumbersOperationCompleted;
        
        private System.Threading.SendOrPostCallback sViewRollNumbersOperationCompleted;
        
        private System.Threading.SendOrPostCallback sViewAttendancesOperationCompleted;
        
        private System.Threading.SendOrPostCallback sAddCourseOperationCompleted;
        
        private System.Threading.SendOrPostCallback sValidParentOperationCompleted;
        
        private System.Threading.SendOrPostCallback sViewCoursesOperationCompleted;
        
        private System.Threading.SendOrPostCallback sValidStudentOperationCompleted;
        
        private System.Threading.SendOrPostCallback sGetStudentInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback sViewAllCoursesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::SMS.Properties.Settings.Default.SMS_server_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sSetDefaultAdminCompletedEventHandler sSetDefaultAdminCompleted;
        
        /// <remarks/>
        public event sChangeLibrarianCompletedEventHandler sChangeLibrarianCompleted;
        
        /// <remarks/>
        public event sValidAdminCompletedEventHandler sValidAdminCompleted;
        
        /// <remarks/>
        public event sAddParentCompletedEventHandler sAddParentCompleted;
        
        /// <remarks/>
        public event sAddStudentCompletedEventHandler sAddStudentCompleted;
        
        /// <remarks/>
        public event sValidLibrarianCompletedEventHandler sValidLibrarianCompleted;
        
        /// <remarks/>
        public event sViewAllBooksCompletedEventHandler sViewAllBooksCompleted;
        
        /// <remarks/>
        public event sViewBookByNameCompletedEventHandler sViewBookByNameCompleted;
        
        /// <remarks/>
        public event sViewBookByAuthorCompletedEventHandler sViewBookByAuthorCompleted;
        
        /// <remarks/>
        public event sAddBookCompletedEventHandler sAddBookCompleted;
        
        /// <remarks/>
        public event sRemoveBookCompletedEventHandler sRemoveBookCompleted;
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event sViewBookNamesCompletedEventHandler sViewBookNamesCompleted;
        
        /// <remarks/>
        public event sMarkAttendanceEmployeeCompletedEventHandler sMarkAttendanceEmployeeCompleted;
        
        /// <remarks/>
        public event sViewEmployeeNumbersCompletedEventHandler sViewEmployeeNumbersCompleted;
        
        /// <remarks/>
        public event sViewRollNumbersCompletedEventHandler sViewRollNumbersCompleted;
        
        /// <remarks/>
        public event sViewAttendancesCompletedEventHandler sViewAttendancesCompleted;
        
        /// <remarks/>
        public event sAddCourseCompletedEventHandler sAddCourseCompleted;
        
        /// <remarks/>
        public event sValidParentCompletedEventHandler sValidParentCompleted;
        
        /// <remarks/>
        public event sViewCoursesCompletedEventHandler sViewCoursesCompleted;
        
        /// <remarks/>
        public event sValidStudentCompletedEventHandler sValidStudentCompleted;
        
        /// <remarks/>
        public event sGetStudentInformationCompletedEventHandler sGetStudentInformationCompleted;
        
        /// <remarks/>
        public event sViewAllCoursesCompletedEventHandler sViewAllCoursesCompleted;
        
        /// <remarks/>
        public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sSetDefaultAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void sSetDefaultAdmin() {
            this.Invoke("sSetDefaultAdmin", new object[0]);
        }
        
        /// <remarks/>
        public void sSetDefaultAdminAsync() {
            this.sSetDefaultAdminAsync(null);
        }
        
        /// <remarks/>
        public void sSetDefaultAdminAsync(object userState) {
            if ((this.sSetDefaultAdminOperationCompleted == null)) {
                this.sSetDefaultAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsSetDefaultAdminOperationCompleted);
            }
            this.InvokeAsync("sSetDefaultAdmin", new object[0], this.sSetDefaultAdminOperationCompleted, userState);
        }
        
        private void OnsSetDefaultAdminOperationCompleted(object arg) {
            if ((this.sSetDefaultAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sSetDefaultAdminCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sChangeLibrarian", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void sChangeLibrarian([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cnic, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string gender, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mobile_no, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string address, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string date_of_birth, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string joing_date, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string employee_no) {
            this.Invoke("sChangeLibrarian", new object[] {
                        name,
                        cnic,
                        gender,
                        email,
                        mobile_no,
                        address,
                        date_of_birth,
                        joing_date,
                        employee_no});
        }
        
        /// <remarks/>
        public void sChangeLibrarianAsync(string name, string cnic, string gender, string email, string mobile_no, string address, string date_of_birth, string joing_date, string employee_no) {
            this.sChangeLibrarianAsync(name, cnic, gender, email, mobile_no, address, date_of_birth, joing_date, employee_no, null);
        }
        
        /// <remarks/>
        public void sChangeLibrarianAsync(string name, string cnic, string gender, string email, string mobile_no, string address, string date_of_birth, string joing_date, string employee_no, object userState) {
            if ((this.sChangeLibrarianOperationCompleted == null)) {
                this.sChangeLibrarianOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsChangeLibrarianOperationCompleted);
            }
            this.InvokeAsync("sChangeLibrarian", new object[] {
                        name,
                        cnic,
                        gender,
                        email,
                        mobile_no,
                        address,
                        date_of_birth,
                        joing_date,
                        employee_no}, this.sChangeLibrarianOperationCompleted, userState);
        }
        
        private void OnsChangeLibrarianOperationCompleted(object arg) {
            if ((this.sChangeLibrarianCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sChangeLibrarianCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sValidAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void sValidAdmin([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool sValidAdminResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool sValidAdminResultSpecified) {
            object[] results = this.Invoke("sValidAdmin", new object[] {
                        username,
                        password});
            sValidAdminResult = ((bool)(results[0]));
            sValidAdminResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void sValidAdminAsync(string username, string password) {
            this.sValidAdminAsync(username, password, null);
        }
        
        /// <remarks/>
        public void sValidAdminAsync(string username, string password, object userState) {
            if ((this.sValidAdminOperationCompleted == null)) {
                this.sValidAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsValidAdminOperationCompleted);
            }
            this.InvokeAsync("sValidAdmin", new object[] {
                        username,
                        password}, this.sValidAdminOperationCompleted, userState);
        }
        
        private void OnsValidAdminOperationCompleted(object arg) {
            if ((this.sValidAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sValidAdminCompleted(this, new sValidAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sAddParent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void sAddParent([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cnic, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string contact, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string childCnic) {
            this.Invoke("sAddParent", new object[] {
                        name,
                        cnic,
                        contact,
                        childCnic});
        }
        
        /// <remarks/>
        public void sAddParentAsync(string name, string cnic, string contact, string childCnic) {
            this.sAddParentAsync(name, cnic, contact, childCnic, null);
        }
        
        /// <remarks/>
        public void sAddParentAsync(string name, string cnic, string contact, string childCnic, object userState) {
            if ((this.sAddParentOperationCompleted == null)) {
                this.sAddParentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsAddParentOperationCompleted);
            }
            this.InvokeAsync("sAddParent", new object[] {
                        name,
                        cnic,
                        contact,
                        childCnic}, this.sAddParentOperationCompleted, userState);
        }
        
        private void OnsAddParentOperationCompleted(object arg) {
            if ((this.sAddParentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sAddParentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sAddStudent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void sAddStudent([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cnic, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string gender, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string roll_no, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string date_of_birth, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string contact, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")] string[] courseNames, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string address) {
            this.Invoke("sAddStudent", new object[] {
                        name,
                        cnic,
                        gender,
                        email,
                        roll_no,
                        date_of_birth,
                        contact,
                        courseNames,
                        address});
        }
        
        /// <remarks/>
        public void sAddStudentAsync(string name, string cnic, string gender, string email, string roll_no, string date_of_birth, string contact, string[] courseNames, string address) {
            this.sAddStudentAsync(name, cnic, gender, email, roll_no, date_of_birth, contact, courseNames, address, null);
        }
        
        /// <remarks/>
        public void sAddStudentAsync(string name, string cnic, string gender, string email, string roll_no, string date_of_birth, string contact, string[] courseNames, string address, object userState) {
            if ((this.sAddStudentOperationCompleted == null)) {
                this.sAddStudentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsAddStudentOperationCompleted);
            }
            this.InvokeAsync("sAddStudent", new object[] {
                        name,
                        cnic,
                        gender,
                        email,
                        roll_no,
                        date_of_birth,
                        contact,
                        courseNames,
                        address}, this.sAddStudentOperationCompleted, userState);
        }
        
        private void OnsAddStudentOperationCompleted(object arg) {
            if ((this.sAddStudentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sAddStudentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sValidLibrarian", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void sValidLibrarian([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool sValidLibrarianResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool sValidLibrarianResultSpecified) {
            object[] results = this.Invoke("sValidLibrarian", new object[] {
                        email,
                        password});
            sValidLibrarianResult = ((bool)(results[0]));
            sValidLibrarianResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void sValidLibrarianAsync(string email, string password) {
            this.sValidLibrarianAsync(email, password, null);
        }
        
        /// <remarks/>
        public void sValidLibrarianAsync(string email, string password, object userState) {
            if ((this.sValidLibrarianOperationCompleted == null)) {
                this.sValidLibrarianOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsValidLibrarianOperationCompleted);
            }
            this.InvokeAsync("sValidLibrarian", new object[] {
                        email,
                        password}, this.sValidLibrarianOperationCompleted, userState);
        }
        
        private void OnsValidLibrarianOperationCompleted(object arg) {
            if ((this.sValidLibrarianCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sValidLibrarianCompleted(this, new sValidLibrarianCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sViewAllBooks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SMS_WcfService")]
        public Book[] sViewAllBooks() {
            object[] results = this.Invoke("sViewAllBooks", new object[0]);
            return ((Book[])(results[0]));
        }
        
        /// <remarks/>
        public void sViewAllBooksAsync() {
            this.sViewAllBooksAsync(null);
        }
        
        /// <remarks/>
        public void sViewAllBooksAsync(object userState) {
            if ((this.sViewAllBooksOperationCompleted == null)) {
                this.sViewAllBooksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsViewAllBooksOperationCompleted);
            }
            this.InvokeAsync("sViewAllBooks", new object[0], this.sViewAllBooksOperationCompleted, userState);
        }
        
        private void OnsViewAllBooksOperationCompleted(object arg) {
            if ((this.sViewAllBooksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sViewAllBooksCompleted(this, new sViewAllBooksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sViewBookByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SMS_WcfService")]
        public Book[] sViewBookByName([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name) {
            object[] results = this.Invoke("sViewBookByName", new object[] {
                        name});
            return ((Book[])(results[0]));
        }
        
        /// <remarks/>
        public void sViewBookByNameAsync(string name) {
            this.sViewBookByNameAsync(name, null);
        }
        
        /// <remarks/>
        public void sViewBookByNameAsync(string name, object userState) {
            if ((this.sViewBookByNameOperationCompleted == null)) {
                this.sViewBookByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsViewBookByNameOperationCompleted);
            }
            this.InvokeAsync("sViewBookByName", new object[] {
                        name}, this.sViewBookByNameOperationCompleted, userState);
        }
        
        private void OnsViewBookByNameOperationCompleted(object arg) {
            if ((this.sViewBookByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sViewBookByNameCompleted(this, new sViewBookByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sViewBookByAuthor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SMS_WcfService")]
        public Book[] sViewBookByAuthor([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string author) {
            object[] results = this.Invoke("sViewBookByAuthor", new object[] {
                        author});
            return ((Book[])(results[0]));
        }
        
        /// <remarks/>
        public void sViewBookByAuthorAsync(string author) {
            this.sViewBookByAuthorAsync(author, null);
        }
        
        /// <remarks/>
        public void sViewBookByAuthorAsync(string author, object userState) {
            if ((this.sViewBookByAuthorOperationCompleted == null)) {
                this.sViewBookByAuthorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsViewBookByAuthorOperationCompleted);
            }
            this.InvokeAsync("sViewBookByAuthor", new object[] {
                        author}, this.sViewBookByAuthorOperationCompleted, userState);
        }
        
        private void OnsViewBookByAuthorOperationCompleted(object arg) {
            if ((this.sViewBookByAuthorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sViewBookByAuthorCompleted(this, new sViewBookByAuthorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sAddBook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void sAddBook([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string title, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string author) {
            this.Invoke("sAddBook", new object[] {
                        title,
                        author});
        }
        
        /// <remarks/>
        public void sAddBookAsync(string title, string author) {
            this.sAddBookAsync(title, author, null);
        }
        
        /// <remarks/>
        public void sAddBookAsync(string title, string author, object userState) {
            if ((this.sAddBookOperationCompleted == null)) {
                this.sAddBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsAddBookOperationCompleted);
            }
            this.InvokeAsync("sAddBook", new object[] {
                        title,
                        author}, this.sAddBookOperationCompleted, userState);
        }
        
        private void OnsAddBookOperationCompleted(object arg) {
            if ((this.sAddBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sAddBookCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sRemoveBook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void sRemoveBook([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string title, out bool sRemoveBookResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool sRemoveBookResultSpecified) {
            object[] results = this.Invoke("sRemoveBook", new object[] {
                        title});
            sRemoveBookResult = ((bool)(results[0]));
            sRemoveBookResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void sRemoveBookAsync(string title) {
            this.sRemoveBookAsync(title, null);
        }
        
        /// <remarks/>
        public void sRemoveBookAsync(string title, object userState) {
            if ((this.sRemoveBookOperationCompleted == null)) {
                this.sRemoveBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsRemoveBookOperationCompleted);
            }
            this.InvokeAsync("sRemoveBook", new object[] {
                        title}, this.sRemoveBookOperationCompleted, userState);
        }
        
        private void OnsRemoveBookOperationCompleted(object arg) {
            if ((this.sRemoveBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sRemoveBookCompleted(this, new sRemoveBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetData(int value, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valueSpecified) {
            object[] results = this.Invoke("GetData", new object[] {
                        value,
                        valueSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified) {
            this.GetDataAsync(value, valueSpecified, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        value,
                        valueSpecified}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sViewBookNames", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] sViewBookNames() {
            object[] results = this.Invoke("sViewBookNames", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void sViewBookNamesAsync() {
            this.sViewBookNamesAsync(null);
        }
        
        /// <remarks/>
        public void sViewBookNamesAsync(object userState) {
            if ((this.sViewBookNamesOperationCompleted == null)) {
                this.sViewBookNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsViewBookNamesOperationCompleted);
            }
            this.InvokeAsync("sViewBookNames", new object[0], this.sViewBookNamesOperationCompleted, userState);
        }
        
        private void OnsViewBookNamesOperationCompleted(object arg) {
            if ((this.sViewBookNamesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sViewBookNamesCompleted(this, new sViewBookNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sMarkAttendanceEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void sMarkAttendanceEmployee([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string employee_no, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string date, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string status, out bool sMarkAttendanceEmployeeResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool sMarkAttendanceEmployeeResultSpecified) {
            object[] results = this.Invoke("sMarkAttendanceEmployee", new object[] {
                        employee_no,
                        date,
                        status});
            sMarkAttendanceEmployeeResult = ((bool)(results[0]));
            sMarkAttendanceEmployeeResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void sMarkAttendanceEmployeeAsync(string employee_no, string date, string status) {
            this.sMarkAttendanceEmployeeAsync(employee_no, date, status, null);
        }
        
        /// <remarks/>
        public void sMarkAttendanceEmployeeAsync(string employee_no, string date, string status, object userState) {
            if ((this.sMarkAttendanceEmployeeOperationCompleted == null)) {
                this.sMarkAttendanceEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsMarkAttendanceEmployeeOperationCompleted);
            }
            this.InvokeAsync("sMarkAttendanceEmployee", new object[] {
                        employee_no,
                        date,
                        status}, this.sMarkAttendanceEmployeeOperationCompleted, userState);
        }
        
        private void OnsMarkAttendanceEmployeeOperationCompleted(object arg) {
            if ((this.sMarkAttendanceEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sMarkAttendanceEmployeeCompleted(this, new sMarkAttendanceEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sViewEmployeeNumbers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] sViewEmployeeNumbers() {
            object[] results = this.Invoke("sViewEmployeeNumbers", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void sViewEmployeeNumbersAsync() {
            this.sViewEmployeeNumbersAsync(null);
        }
        
        /// <remarks/>
        public void sViewEmployeeNumbersAsync(object userState) {
            if ((this.sViewEmployeeNumbersOperationCompleted == null)) {
                this.sViewEmployeeNumbersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsViewEmployeeNumbersOperationCompleted);
            }
            this.InvokeAsync("sViewEmployeeNumbers", new object[0], this.sViewEmployeeNumbersOperationCompleted, userState);
        }
        
        private void OnsViewEmployeeNumbersOperationCompleted(object arg) {
            if ((this.sViewEmployeeNumbersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sViewEmployeeNumbersCompleted(this, new sViewEmployeeNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sViewRollNumbers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] sViewRollNumbers() {
            object[] results = this.Invoke("sViewRollNumbers", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void sViewRollNumbersAsync() {
            this.sViewRollNumbersAsync(null);
        }
        
        /// <remarks/>
        public void sViewRollNumbersAsync(object userState) {
            if ((this.sViewRollNumbersOperationCompleted == null)) {
                this.sViewRollNumbersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsViewRollNumbersOperationCompleted);
            }
            this.InvokeAsync("sViewRollNumbers", new object[0], this.sViewRollNumbersOperationCompleted, userState);
        }
        
        private void OnsViewRollNumbersOperationCompleted(object arg) {
            if ((this.sViewRollNumbersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sViewRollNumbersCompleted(this, new sViewRollNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sViewAttendances", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SMS_WcfService")]
        public Attendance[] sViewAttendances([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id) {
            object[] results = this.Invoke("sViewAttendances", new object[] {
                        id});
            return ((Attendance[])(results[0]));
        }
        
        /// <remarks/>
        public void sViewAttendancesAsync(string id) {
            this.sViewAttendancesAsync(id, null);
        }
        
        /// <remarks/>
        public void sViewAttendancesAsync(string id, object userState) {
            if ((this.sViewAttendancesOperationCompleted == null)) {
                this.sViewAttendancesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsViewAttendancesOperationCompleted);
            }
            this.InvokeAsync("sViewAttendances", new object[] {
                        id}, this.sViewAttendancesOperationCompleted, userState);
        }
        
        private void OnsViewAttendancesOperationCompleted(object arg) {
            if ((this.sViewAttendancesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sViewAttendancesCompleted(this, new sViewAttendancesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sAddCourse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void sAddCourse([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name) {
            this.Invoke("sAddCourse", new object[] {
                        name});
        }
        
        /// <remarks/>
        public void sAddCourseAsync(string name) {
            this.sAddCourseAsync(name, null);
        }
        
        /// <remarks/>
        public void sAddCourseAsync(string name, object userState) {
            if ((this.sAddCourseOperationCompleted == null)) {
                this.sAddCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsAddCourseOperationCompleted);
            }
            this.InvokeAsync("sAddCourse", new object[] {
                        name}, this.sAddCourseOperationCompleted, userState);
        }
        
        private void OnsAddCourseOperationCompleted(object arg) {
            if ((this.sAddCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sAddCourseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sValidParent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void sValidParent([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cnic, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool sValidParentResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool sValidParentResultSpecified) {
            object[] results = this.Invoke("sValidParent", new object[] {
                        cnic,
                        password});
            sValidParentResult = ((bool)(results[0]));
            sValidParentResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void sValidParentAsync(string cnic, string password) {
            this.sValidParentAsync(cnic, password, null);
        }
        
        /// <remarks/>
        public void sValidParentAsync(string cnic, string password, object userState) {
            if ((this.sValidParentOperationCompleted == null)) {
                this.sValidParentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsValidParentOperationCompleted);
            }
            this.InvokeAsync("sValidParent", new object[] {
                        cnic,
                        password}, this.sValidParentOperationCompleted, userState);
        }
        
        private void OnsValidParentOperationCompleted(object arg) {
            if ((this.sValidParentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sValidParentCompleted(this, new sValidParentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sViewCourses", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] sViewCourses() {
            object[] results = this.Invoke("sViewCourses", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void sViewCoursesAsync() {
            this.sViewCoursesAsync(null);
        }
        
        /// <remarks/>
        public void sViewCoursesAsync(object userState) {
            if ((this.sViewCoursesOperationCompleted == null)) {
                this.sViewCoursesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsViewCoursesOperationCompleted);
            }
            this.InvokeAsync("sViewCourses", new object[0], this.sViewCoursesOperationCompleted, userState);
        }
        
        private void OnsViewCoursesOperationCompleted(object arg) {
            if ((this.sViewCoursesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sViewCoursesCompleted(this, new sViewCoursesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sValidStudent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void sValidStudent([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string roll_no, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool sValidStudentResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool sValidStudentResultSpecified) {
            object[] results = this.Invoke("sValidStudent", new object[] {
                        roll_no,
                        password});
            sValidStudentResult = ((bool)(results[0]));
            sValidStudentResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void sValidStudentAsync(string roll_no, string password) {
            this.sValidStudentAsync(roll_no, password, null);
        }
        
        /// <remarks/>
        public void sValidStudentAsync(string roll_no, string password, object userState) {
            if ((this.sValidStudentOperationCompleted == null)) {
                this.sValidStudentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsValidStudentOperationCompleted);
            }
            this.InvokeAsync("sValidStudent", new object[] {
                        roll_no,
                        password}, this.sValidStudentOperationCompleted, userState);
        }
        
        private void OnsValidStudentOperationCompleted(object arg) {
            if ((this.sValidStudentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sValidStudentCompleted(this, new sValidStudentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sGetStudentInformation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] sGetStudentInformation() {
            object[] results = this.Invoke("sGetStudentInformation", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void sGetStudentInformationAsync() {
            this.sGetStudentInformationAsync(null);
        }
        
        /// <remarks/>
        public void sGetStudentInformationAsync(object userState) {
            if ((this.sGetStudentInformationOperationCompleted == null)) {
                this.sGetStudentInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsGetStudentInformationOperationCompleted);
            }
            this.InvokeAsync("sGetStudentInformation", new object[0], this.sGetStudentInformationOperationCompleted, userState);
        }
        
        private void OnsGetStudentInformationOperationCompleted(object arg) {
            if ((this.sGetStudentInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sGetStudentInformationCompleted(this, new sGetStudentInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sViewAllCourses", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SMS_WcfService")]
        public Course[] sViewAllCourses() {
            object[] results = this.Invoke("sViewAllCourses", new object[0]);
            return ((Course[])(results[0]));
        }
        
        /// <remarks/>
        public void sViewAllCoursesAsync() {
            this.sViewAllCoursesAsync(null);
        }
        
        /// <remarks/>
        public void sViewAllCoursesAsync(object userState) {
            if ((this.sViewAllCoursesOperationCompleted == null)) {
                this.sViewAllCoursesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsViewAllCoursesOperationCompleted);
            }
            this.InvokeAsync("sViewAllCourses", new object[0], this.sViewAllCoursesOperationCompleted, userState);
        }
        
        private void OnsViewAllCoursesOperationCompleted(object arg) {
            if ((this.sViewAllCoursesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sViewAllCoursesCompleted(this, new sViewAllCoursesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetDataUsingDataContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CompositeType GetDataUsingDataContract([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CompositeType composite) {
            object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                        composite});
            return ((CompositeType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
            if ((this.GetDataUsingDataContractOperationCompleted == null)) {
                this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
            }
            this.InvokeAsync("GetDataUsingDataContract", new object[] {
                        composite}, this.GetDataUsingDataContractOperationCompleted, userState);
        }
        
        private void OnGetDataUsingDataContractOperationCompleted(object arg) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SMS_WcfService")]
    public partial class Book {
        
        private string authorField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SMS_WcfService")]
    public partial class CompositeType {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Drawing")]
    public partial class Image {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlQualifiedName factoryTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        public System.Xml.XmlQualifiedName FactoryType {
            get {
                return this.factoryTypeField;
            }
            set {
                this.factoryTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SMS_WcfService")]
    public partial class Message {
        
        private string messageTextField;
        
        private Person senderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MessageText {
            get {
                return this.messageTextField;
            }
            set {
                this.messageTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Person Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Teacher))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SMS_WcfService")]
    public partial class Person {
        
        private string addressField;
        
        private string cnicField;
        
        private string date_of_birthField;
        
        private string emailField;
        
        private string genderField;
        
        private Message[] inboxField;
        
        private string mobile_noField;
        
        private string nameField;
        
        private string passwordField;
        
        private Image pictureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cnic {
            get {
                return this.cnicField;
            }
            set {
                this.cnicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Date_of_birth {
            get {
                return this.date_of_birthField;
            }
            set {
                this.date_of_birthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Message[] Inbox {
            get {
                return this.inboxField;
            }
            set {
                this.inboxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Mobile_no {
            get {
                return this.mobile_noField;
            }
            set {
                this.mobile_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Image Picture {
            get {
                return this.pictureField;
            }
            set {
                this.pictureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Teacher))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SMS_WcfService")]
    public partial class Employee : Person {
        
        private Attendance[] attendancesField;
        
        private string employee_noField;
        
        private string joining_dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Attendance[] Attendances {
            get {
                return this.attendancesField;
            }
            set {
                this.attendancesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Employee_no {
            get {
                return this.employee_noField;
            }
            set {
                this.employee_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Joining_date {
            get {
                return this.joining_dateField;
            }
            set {
                this.joining_dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SMS_WcfService")]
    public partial class Attendance {
        
        private string dateField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SMS_WcfService")]
    public partial class Teacher : Employee {
        
        private Course[] assignedCoursesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Course[] AssignedCourses {
            get {
                return this.assignedCoursesField;
            }
            set {
                this.assignedCoursesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SMS_WcfService")]
    public partial class Course {
        
        private Teacher teacherField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Teacher Teacher {
            get {
                return this.teacherField;
            }
            set {
                this.teacherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sSetDefaultAdminCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sChangeLibrarianCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sValidAdminCompletedEventHandler(object sender, sValidAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sValidAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sValidAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool sValidAdminResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool sValidAdminResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sAddParentCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sAddStudentCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sValidLibrarianCompletedEventHandler(object sender, sValidLibrarianCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sValidLibrarianCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sValidLibrarianCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool sValidLibrarianResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool sValidLibrarianResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sViewAllBooksCompletedEventHandler(object sender, sViewAllBooksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sViewAllBooksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sViewAllBooksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Book[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Book[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sViewBookByNameCompletedEventHandler(object sender, sViewBookByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sViewBookByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sViewBookByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Book[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Book[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sViewBookByAuthorCompletedEventHandler(object sender, sViewBookByAuthorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sViewBookByAuthorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sViewBookByAuthorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Book[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Book[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sAddBookCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sRemoveBookCompletedEventHandler(object sender, sRemoveBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sRemoveBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sRemoveBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool sRemoveBookResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool sRemoveBookResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sViewBookNamesCompletedEventHandler(object sender, sViewBookNamesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sViewBookNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sViewBookNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sMarkAttendanceEmployeeCompletedEventHandler(object sender, sMarkAttendanceEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sMarkAttendanceEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sMarkAttendanceEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool sMarkAttendanceEmployeeResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool sMarkAttendanceEmployeeResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sViewEmployeeNumbersCompletedEventHandler(object sender, sViewEmployeeNumbersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sViewEmployeeNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sViewEmployeeNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sViewRollNumbersCompletedEventHandler(object sender, sViewRollNumbersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sViewRollNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sViewRollNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sViewAttendancesCompletedEventHandler(object sender, sViewAttendancesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sViewAttendancesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sViewAttendancesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Attendance[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Attendance[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sAddCourseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sValidParentCompletedEventHandler(object sender, sValidParentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sValidParentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sValidParentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool sValidParentResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool sValidParentResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sViewCoursesCompletedEventHandler(object sender, sViewCoursesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sViewCoursesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sViewCoursesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sValidStudentCompletedEventHandler(object sender, sValidStudentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sValidStudentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sValidStudentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool sValidStudentResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool sValidStudentResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sGetStudentInformationCompletedEventHandler(object sender, sGetStudentInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sGetStudentInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sGetStudentInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sViewAllCoursesCompletedEventHandler(object sender, sViewAllCoursesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sViewAllCoursesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sViewAllCoursesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Course[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Course[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompositeType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompositeType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591